const { dataHelper } = require('../../src/components/ApplicationDateChart/dataHelper');

describe('validateValue', () => {
  test('Все заявки в январе', () => {
    expect(
      dataHelper([
        {
          id: 1,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 2,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 3,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 4,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 5,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 6,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 7,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 8,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 9,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 10,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 11,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 12,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
        {
          id: 13,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.01.2023',
        },
      ]),
    ).toEqual({
      January: 13,
      February: 0,
      March: 0,
      April: 0,
      May: 0,
      June: 0,
      July: 0,
      August: 0,
      September: 0,
      October: 0,
      November: 0,
      December: 0,
    });
  });
  test('Все заявки в декабре', () => {
    expect(
      dataHelper([
        {
          id: 1,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 2,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 3,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 4,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 5,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 6,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 7,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 8,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 9,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 10,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 11,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 12,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
        {
          id: 13,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.12.2023',
        },
      ]),
    ).toEqual({
      January: 0,
      February: 0,
      March: 0,
      April: 0,
      May: 0,
      June: 0,
      July: 0,
      August: 0,
      September: 0,
      October: 0,
      November: 0,
      December: 13,
    });
  });
  test('Ве заявки в 13 месяце', () => {
    expect(
      dataHelper([
        {
          id: 1,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 2,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 3,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 4,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 5,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 6,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 7,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 8,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 9,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 10,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 11,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 12,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
        {
          id: 13,
          surname: 'Рогалев',
          name: 'Руслан',
          patronymic: 'Евгеньевич',
          birthDate: '21.04.1998',
          applicationDate: '23.13.2023',
        },
      ]),
    ).toEqual({
      January: 0,
      February: 0,
      March: 0,
      April: 0,
      May: 0,
      June: 0,
      July: 0,
      August: 0,
      September: 0,
      October: 0,
      November: 0,
      December: 0,
    });
  });
});

describe('unvalidateValue', () => {
  test('Массив с некорректными значениями', () => {
    expect(
      dataHelper([
        {
          a: 1,
          b: 'Рогалев',
          c: 'Руслан',
          patronymic: 'Евгеньевич',
        },
      ]),
    ).toEqual({
      January: 0,
      February: 0,
      March: 0,
      April: 0,
      May: 0,
      June: 0,
      July: 0,
      August: 0,
      September: 0,
      October: 0,
      November: 0,
      December: 0,
    });
  });
  test('Пустой массив', () => {
    expect(dataHelper([])).toEqual({
      January: 0,
      February: 0,
      March: 0,
      April: 0,
      May: 0,
      June: 0,
      July: 0,
      August: 0,
      September: 0,
      October: 0,
      November: 0,
      December: 0,
    });
  });
});
